### ISSUE TITLE
Any luck with a swift version? 

### ISSUE THREAD

**Issue by grantkemp** [pusher/pusher-test-iOS#5]
Any luck with a swift version?  or docs?

**Comment by leggetter** [comment]
https://github.com/pusher-community/pusher-websocket-swift and @hamchapman is your man!

**Comment by lukeredpath** [comment]
libPusher will eventually support Swift properly (and I may re-write it too now I'm getting more comfortable with Swift), its just a case of finding the time.

**Comment by leggetter** [comment]
:+1:

**Comment by grantkemp** [comment]
@leggetter  Long time! Thanks for the help

@lukeredpath I will try it out with pods and share feedback if it helps.  Will it work out of the box with out major changes if i use a bridging header?

**Comment by hamchapman** [comment]
@grantkemp I think if you add `use_frameworks!` to your Podfile then you won't even need a bridging header
